<craft name="tag">
    <parameter name="width" type="int" default="15"/>
    <parameter name="length" type="int" default="20"/>
    <parameter name="height" type="int" default="2"/>
    <parameter name="type" type="int" default="2"/>
    <parameter name="indent" type="int" default="1"/>
    
    <g transform="mirrorY()">
        <script type="text/openjscad">
            function main() {
                // handles different tag types
                if (params.type == 1) { params.type = 4; }
                
                else if (params.type == 2) { params.type = 6; }
                
                else { params.type = 100; }
    
                // handles minimum values
                if (params.width < 8) { params.width = 8; }
                if (params.length < 5) { params.length = 5; }
                
                // assembled tag
                return difference(
                    body(),
                    hole()
                );
                
                // tag components
                function body() {
                    var b, top, topDiff, indentDiff;
                
                    // parts
                    b = cube({
                        size: [params.width, params.length, params.height],
                        round: false,
                        center: true
                    });
                    
                    top = cylinder({
                        r: params.width / 2,
                        h: params.height,
                        fn: params.type,
                        center: true
                    });
                    
                    topDiff = cube({
                        size: [params.width, params.width, params.height],
                        center: true
                    });
    
                    // transformations
                    top = top.translate([0, params.length / 2, 0]);
                    top = difference(
                        top,
                        topDiff.translate([0, -params.width/2, 0])
                    );
                    
                    b = union(top, b);
    
                    // handles indent parameter
                    if (params.indent) {
                        indentDiff = cube({
                            size: [params.width - 2, params.length - 2, params.height],
                            center: true
                        });
                        
                        b = difference(
                            b,
                            indentDiff.translate([0, 0, params.height - 1])
                        );
                    }
                    
                    return b;
                }
                
                function hole() {
                    // parts
                    return cylinder({
                        r: 1,
                        h: params.height * 2,
                        center: true
                    }).translate([0, (params.length / 2) + (params.width / 4), -1]);
                }
            }
        </script>
    </g>
    
</craft>